### ISSUE TITLE
new repo for post harvest wheel-ruts semantic segmentation using drone RGB data

### ISSUE THREAD

**Issue by stefp** [b-lack/ThePirateForest#4]
Hi, here is a new repo (
https://github.com/SmartForest-no/wheelRuts_semanticSegmentation) to do semantic segmentation of post-harvest drone images. The method is described in the following paper: https://academic.oup.com/forestry/advance-article/doi/10.1093/forestry/cpac023/6627280?login=true

Cheers to all the pirates out there :)

**Comment by b-lack** [comment]
@stefp @sabh92 YOU ARE A PIRATE
